import { TaskDTO } from "../../_dto/types";

export const tasks: TaskDTO[] = [
    {
        id: 1,
        user_id: 101,
        title: "Finish frontend UI",
        due_on: new Date("2025-01-10").toISOString(),
        status: "completed",
    },
    {
        id: 2,
        user_id: 101,
        title: "Prepare API documentation",
        due_on: new Date("2025-01-14").toISOString(),
        status: "completed",
    },
    {
        id: 3,
        user_id: 101,
        title: "Fix authentication bug",
        due_on: new Date("2025-02-01").toISOString(),
        status: "pending",
    },
    {
        id: 4,
        user_id: 101,
        title: "Review database schema",
        due_on: new Date("2025-02-05").toISOString(),
        status: "pending",
    },
    {
        id: 5,
        user_id: 102,
        title: "Deploy staging server",
        due_on: new Date("2025-01-05").toISOString(),
        status: "completed",
    },
    {
        id: 6,
        user_id: 102,
        title: "Run unit tests",
        due_on: new Date("2025-02-08").toISOString(),
        status: "pending",
    },
    {
        id: 7,
        user_id: 102,
        title: "Write task automation scripts",
        due_on: new Date("2025-01-20").toISOString(),
        status: "completed",
    },
    {
        id: 8,
        user_id: 103,
        title: "Optimize API response time",
        due_on: new Date("2025-02-10").toISOString(),
        status: "pending",
    },
    {
        id: 9,
        user_id: 103,
        title: "Update user onboarding flow",
        due_on: new Date("2025-01-12").toISOString(),
        status: "completed",
    },
    {
        id: 10,
        user_id: 103,
        title: "Test payment integration",
        due_on: new Date("2025-02-15").toISOString(),
        status: "pending",
    },
    {
        id: 11,
        user_id: 104,
        title: "Create Documentation for payment system",
        due_on: new Date("2025-03-22").toISOString(),
        status: "completed",
    },
];
